export enum TicketType {
  GENERAL = 'GENERAL',
  INVOICE = 'INVOICE',
  ISSUE = 'ISSUE',
  TASK = "TASK",
  BUG = 'BUG',
  TEST = 'TEST',
  EVENT = 'EVENT',
  RELEASE = 'RELEASE',
  SUPPORT = 'SUPPORT',
  SECURITY = 'SECURITY',
  FEATURE = 'FEATURE_REQUEST',
  PERFORMANCE = 'PERFORMANCE',
  MAINTENANCE = 'MAINTENANCE',
  OPTIMIZATION = 'OPTIMIZATION',
  DOCUMENTATION = 'DOCUMENTATION'
}

export enum TicketPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum TicketStatus {
  UPCOMING = "UPCOMING",
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CANCELLED = "CANCELLED",
  CLOSED = "CLOSED",
}
