export const TICKET_TYPES = [
  'GENERAL',
  'BUG',
  'FEATURE_REQUEST',
  'DOCUMENTATION',
  'SUPPORT',
  'TASK',
  'ISSUE',
  'INVOICE',
  'MEETING',
  'EVENT',
  'OPTIMIZATION',
  'MAINTENANCE',
  'RESEARCH',
  'TEST',
  'RELEASE',
  'SECURITY',
  'DEPLOYMENT',
  'PERFORMANCE',
  'DESIGN',
  'TICKET',
];

export const TICKET_PRIORITIES = ['LOW','MEDIUM','HIGH','URGENT']

export const TAG_SUGGESTIONS = [
  'API',
  'SWE',
  'accessibility',
  'analytics',
  'algorithm',
  'backend',
  'bug fix',
  'beta',
  'button',
  'client',
  'cloud',
  'code',
  'comment',
  'config',
  'database',
  'deploy',
  'design',
  'dev',
  'docs',
  'error',
  'feature request',
  'first issue',
  'frontend',
  'git',
  'integration',
  'layout',
  'logging',
  'migration',
  'new feature',
  'optimization',
  'payment',
  'performance',
  'prod',
  'refactor',
  'security',
  'slack',
  'staging',
  'style',
  'system design',
  'testing',
  'ui/ux',
  'v1',
  'v2',
];

export const TICKET_STATUSES = ['UPCOMING', 'IN_PROGRESS', 'OPEN', 'RESOLVED', 'CLOSED', 'CANCELLED'];