export const TICKET_TYPES = [
  'GENERAL',
  'BUG',
  'FEATURE_REQUEST',
  'DOCUMENTATION',
  'SUPPORT',
  'ISSUE',
  'INVOICE',
  'OPTIMIZATION',
  'MAINTENANCE',
  'RESEARCH',
  'TEST',
  'SECURITY',
  'PERFORMANCE',
  'DESIGN',
  'TICKET',
];

export const PLANNER_TASK_TYPES = [
  'TASK',
  'MEETING',
  'EVENT',
  'RELEASE',
  'DEPLOYMENT',
];

export const TICKET_PRIORITIES = [
  'LOW',
  'MEDIUM',
  'HIGH',
  'URGENT'
]

export const TAG_SUGGESTIONS = [
  'API',
  'SWE',
  'accessibility',
  'analytics',
  'algorithm',
  'backend',
  'bug fix',
  'beta',
  'button',
  'client',
  'cloud',
  'code',
  'comment',
  'config',
  'database',
  'deploy',
  'design',
  'dev',
  'docs',
  'error',
  'feature request',
  'first issue',
  'frontend',
  'git',
  'integration',
  'layout',
  'logging',
  'migration',
  'new feature',
  'optimization',
  'payment',
  'performance',
  'prod',
  'refactor',
  'security',
  'slack',
  'staging',
  'style',
  'system design',
  'testing',
  'ui/ux',
  'v1',
  'v2',
];

export const EVENT_TAG_SUGGESTIONS = [
  'meeting',
  'workshop',
  'webinar',
  'conference',
  'seminar',
  'training',
  'demo',
  'presentation',
  'standup',
  'retrospective',
  'planning',
  'review',
  'kickoff',
  'onboarding',
  'blocked',
  'remote',
  'in-person',
  'hybrid',
  'zoom',
  'google meet',
  'office',
  'conference room',
  'stakeholders',
  'leadership',
  'customers',
  'partners',
  'public',
  'brainstorm',
  'feedback',
  'decision',
  'alignment',
  'sync',
  'follow-up',
  'celebration',
  'milestone',
  'launch',
];

export const TICKET_STATUSES = ['UPCOMING', 'IN_PROGRESS', 'OPEN', 'RESOLVED', 'CLOSED', 'CANCELLED'];

export const TICKET_LIST_HEADERS = ['No.', 'Title', 'Priority', 'Status', 'Type', 'Due Date', 'Last Updated']

export const TASK_LIST_HEADERS = ['No.', 'Title', 'Status', 'Type', 'Due Date', ]