import { Ticket_Type, Ticket_Priority, Ticket} from '@/types/ticket';

export const DB: Ticket[] = [
  { 
    id: 't1', 
    title: 'Kanban board v1 bug', 
    description: 'Modules not found. Issue is between package and client runtime.', 
    status: 'OPEN',
    priority: Ticket_Priority.MEDIUM, 
    type: Ticket_Type.FEATURE,
    createdAt: '2025-10-01T09:12:00Z', 
    updatedAt: '2025-10-02T10:00:00Z', 
    assignedToId: 1, 
    tags: ['dnd/core','node_modules', 'react', 'next'], 
    dueDate: '2025-12-12' 
  },
  { id: 't2', 
    title: 'Admin Dashboard Design', 
    description: 'Design md, lg and mobile dashboard UI for admin.', 
    status: 'UPCOMING', 
    priority: Ticket_Priority.MEDIUM, 
    type: Ticket_Type.FEATURE,
    createdAt: '2025-10-09T12:00:00Z', 
    updatedAt: '2025-10-20T12:00:00Z', 
    assignedToId: null, 
    tags: ['UI/ UX','design', 'frontend'], 
    dueDate: '2025-11-11' 
  },
  { 
    id: 't3', 
    title: 'Tickets: Dashboard Overview', 
    description: 'Build ticket page as home with md, lg and mobile responsiveness.', 
    status: 'IN_PROGRESS', 
    priority: Ticket_Priority.HIGH, 
    type: Ticket_Type.GENERAL,
    createdAt: '2025-09-25T15:22:00Z', 
    updatedAt: '2025-10-03T08:40:00Z', 
    assignedToId: 3, 
    tags: ['dashboard', 'design', 'UI/UX', 'mobile-friendly'], 
    dueDate: '2025-11-01' 
  },
  { 
    id: 't4', 
    title: 'Double api call, race conditions', 
    description: 'client component makes double api calls on (re)render causing error in app-breaking api event.', 
    status: 'RESOLVED', 
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.BUG,
    createdAt: '2025-10-15T10:00:00Z', 
    updatedAt: '2025-10-17T09:30:00Z', 
    assignedToId: 6, 
    tags: ['react', 'useffect', 'express'] 
  },
  { 
    id: 't5', 
    title: 'Web hooks: Slack and SMS channel selection', 
    description: 'Select Slack channel per workspace.', 
    status: 'OPEN', 
    priority: Ticket_Priority.LOW, 
    type: Ticket_Type.RELEASE,
    createdAt: '2025-10-03T11:01:00Z', 
    updatedAt: '2025-10-03T11:01:00Z', 
    tags: ['integration','slack', 'sms'] 
  },
  { 
    id: 't9', 
    title: 'Dashboard Authbar Avatar', 
    description: 'Set color variants for Teams, User.organization and Admins.', 
    status: 'UPCOMING', 
    priority: Ticket_Priority.LOW, 
    type: Ticket_Type.FEATURE,
    createdAt: '2025-09-28T09:00:00Z', 
    updatedAt: '2025-09-28T09:00:00Z', 
    assignedToId: 2, 
    tags: ['ui','avatar'],
    dueDate: '2025-11-10' 
  },
  { 
    id: 'i2', 
    title: 'Ticket API controllers', 
    description: 'Write REST functions for client-api live stream, tickets overview sync and data update', 
    status: 'UPCOMING', 
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.GENERAL,
    createdAt: '2025-09-28T09:00:00Z', 
    updatedAt: '2025-09-28T09:00:00Z', 
    assignedToId: 2, 
    tags: ['events','api', 'rest', 'express'] ,
    dueDate: '2025-10-22' 
  },
    { 
    id: 't6', 
    title: 'Console.log cleanup', 
    description: 'Clean up all trailing logs and unnecessary console.logs', 
    status: 'UPCOMING', 
    priority: Ticket_Priority.LOW, 
    type: Ticket_Type.EVENT,
    createdAt: '2025-09-28T09:00:00Z', 
    updatedAt: '2025-09-28T09:00:00Z', 
    assignedToId: 2, 
    tags: ['refactor', 'console.log', 'cleanup',] 
  },
  { 
    id: 't7',
    title: 'Resolve Hydration mismatch', 
    description: 'Trace the source of server vs client HTML render mis-match.', 
    status: 'OPEN', 
    priority: Ticket_Priority.MEDIUM, 
    type: Ticket_Type.BUG,
    createdAt: '2025-06-01T09:00:00Z', 
    updatedAt: '2025-07-01T09:00:00Z', 
    tags: ['hydration', 'react', 'client', 'server', 'next', 'HTML'] 
  },
  {
    id: 't11',
    title: "Kanban board, hello-pangea/dnd",
    description: "Module not found. Package install error. Resolved by classic 'rm -rf .next node_modules package-lock.json npm install' ",
    status: "RESOLVED",
    priority: Ticket_Priority.HIGH,
    type: Ticket_Type.ISSUE,
    createdAt: "2025-10-20T08:13:00Z",
    updatedAt: "2025-10-20T09:14:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ['react', 'module', 'package', 'next'],
  },
  {
    id: 't12',
    title: "NextAuth & auth flow",
    description: "Fix nextAuth Credentials error and resolve client to server authentication flow.",
    status: "RESOLVED",
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.BUG,
    createdAt: "2025-10-18T08:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["frontend","design"],
  },
  {
    id: 't13',
    title: "TicTask, User Dashboard",
    description: "Start building out TicTask Dashboard with users: personal and team view.",
    status: "OPEN",
    priority: Ticket_Priority.HIGH,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-10-12T08:00:00Z",
    updatedAt: "2025-10-20T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["frontend", "design", 'client-server'],
    dueDate: '2025-10-29',
  },
  {
    id: 't14',
    title: "TicTask SWE Expo",
    description: "Record every thought, reason and bias toward my TicTask bug fixing and learning curve experience.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.DOCUMENTATION,
    createdAt: "2025-10-15T08:00:00Z",
    updatedAt: "2025-10-20T09:00:00Z",
    createdById: 1,
    assignedToId: 2,
    tags: ["dev","SWE", 'documentation'],
  },
  {
    id: 't15',
    title: "DevEx Journal",
    description: "Document my experience with bug fixes, frustrations and learning curve.",
    status: "CANCELLED",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.DOCUMENTATION,
    createdAt: "2025-10-15T08:00:00Z",
    updatedAt: "2025-10-20T09:00:00Z",
    createdById: 1,
    assignedToId: 2,
    tags: ["docs","dev", 'experience'],
  },
  {
    id: 't16',
    title: "Dashboard Pages (12+)",
    description: "Build out all menu pages, sections on dashboard with inherit styles in mind.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-10-15T08:00:00Z",
    updatedAt: "2025-09-20T09:00:00Z",
    createdById: 3,
    assignedToId: 'Akachukwu.Obiaju',
    dueDate: '2025-10-30',
    tags: ["frontend","ui/ ux", 'design', 'pages'],
  },
  { 
    id: 't8', 
    title: 'Dashboard layout and flow tree', 
    description: 'Design dashboard data structure, layout and flow tree.', 
    status: 'CLOSED',
    priority: Ticket_Priority.HIGH, 
    type: Ticket_Type.PERFORMANCE,
    createdAt: '2025-10-08T09:00:00Z', 
    updatedAt: '2025-10-17T12:30:00Z', 
    assignedToId: 1, 
    tags: ['system design','frontend', 'layout'] 
  },
  { 
    id: 't17', 
    title: 'Landing Page', 
    description: 'Build the index page. This event set the tempo for the rest of the app building', 
    status: 'CLOSED',
    priority: Ticket_Priority.HIGH,  
    type: Ticket_Type.GENERAL,
    createdAt: '2025-09-10T09:00:00Z', 
    updatedAt: '2025-09-29T12:30:00Z', 
    assignedToId: 1, 
    tags: ['ui/ux', 'design'] 
  },
  { 
    id: 't18', 
    title: 'Auth Pages', 
    description: 'Build login, register and other auth pages from the front. Design the client with backend data structure in mind', 
    status: 'CLOSED',
    priority: Ticket_Priority.HIGH, 
    type: Ticket_Type.GENERAL,
    createdAt: '2025-09-18T01:00:00Z', 
    updatedAt: '2025-09-26T12:30:00Z', 
    assignedToId: 1, 
    tags: ['ui/ux', 'next', 'frontend'] 
  },
  { 
    id: 't19', 
    title: 'TicTask Backend design', 
    description: 'Design TicTask Overall System. App heirachy. Data structure and algorithms. File system, routes and controllers, REST apis and other utility functions. Consider all SWE principles', 
    status: 'CLOSED', 
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.PERFORMANCE,
    createdAt: '2025-09-04T01:00:00Z', 
    updatedAt: '2025-09-22T12:30:00Z', 
    assignedToId: 1, 
    tags: ['backend', 'dsa', 'system design', 'SWE'] 
  },
  { 
    id: 't10', 
    title: 'App theme: background, colors variations', 
    description: 'Design app baseline styles with mui and css for inherit colors and bgColors', 
    status: 'CLOSED', 
    priority: Ticket_Priority.MEDIUM, 
    type: Ticket_Type.OPTIMIZATION,
    createdAt: '2025-10-18T09:00:00Z', 
    updatedAt: '2025-10-20T12:30:00Z', 
    assignedToId: 1, 
    tags: ['ui/ux', 'css', 'material-ui'] 
  },
  { 
    id: 'i1', 
    title: 'Deploy backend to prod', 
    description: 'Bundle and deploy backend to production via render, railway or AWS', 
    status: 'UPCOMING', 
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.EVENT,
    createdAt: '2025-10-20T21:05:00Z', 
    updatedAt: '2025-10-20T21:10:00Z', 
    assignedToId: 1, 
    tags: ['backend', 'prod', 'aws'] 
  },
  { 
    id: 't20', 
    title: 'Layouts nesting mixup', 
    description: 'Root layout vs nested layout causing background mismatch and inherit issues', 
    status: 'RESOLVED',
    priority: Ticket_Priority.URGENT, 
    type: Ticket_Type.BUG,
    createdAt: '2025-10-18T20:00:00Z', 
    updatedAt: '2025-10-19T12:30:00Z', 
    assignedToId: 1, 
    tags: ['ui/ux', 'next', 'HTML'] 
  },
];

export const mockTickets = [
  {
    id: 1,
    title: "Onboarding email not delivered",
    description: "Users report signup email not arriving.",
    status: "OPEN",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.BUG,
    createdAt: "2025-10-01T09:12:00Z",
    updatedAt: "2025-10-02T10:00:00Z",
    createdById: 2,
    assignedToId: 1,
    clientId: null,
    dueDate: "2025-10-10",
    tags: ["email","auth"],
  },
  {
    id: 2,
    title: "Mobile nav redesign",
    description: "Redesign mobile navigation for better reachability.",
    status: "UPCOMING",
    priority: Ticket_Priority.MEDIUM,
    type: "FEATURE_REQUEST",
    createdAt: "2025-09-20T12:00:00Z",
    updatedAt: "2025-09-20T12:00:00Z",
    createdById: 1,
    assignedToId: null,
    clientId: null,
    dueDate: "2025-11-01",
    tags: ["ui","mobile"],
  },
  {
    id: 3,
    title: "Payment retry bug",
    description: "Retry logic fails when network interrupts.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.BUG,
    createdAt: "2025-09-25T15:22:00Z",
    updatedAt: "2025-10-03T08:40:00Z",
    createdById: 4,
    assignedToId: 3,
    clientId: 5,
    dueDate: "2025-10-05",
    tags: ["payments"],
  },
  {
    id: 4,
    title: "Invoice export CSV",
    description: "Add CSV export for invoices in reports.",
    status: "RESOLVED",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-10T10:00:00Z",
    updatedAt: "2025-09-01T09:30:00Z",
    createdById: 2,
    assignedToId: 6,
    clientId: null,
    tags: ["export"],
  },
  {
    id: 5,
    title: "Slack integration: channel selection",
    description: "Allow selecting Slack channel per workspace for notifications.",
    status: "OPEN",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.SUPPORT,
    createdAt: "2025-10-03T11:01:00Z",
    updatedAt: "2025-10-03T11:01:00Z",
    createdById: 1,
    assignedToId: null,
    tags: ["integration","slack"],
  },
  {
    id: 6,
    title: "Event reminder cron",
    description: "Scheduled job to remind attendees 24 hours before event.",
    status: "UPCOMING",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.EVENT,
    createdAt: "2025-09-28T09:00:00Z",
    updatedAt: "2025-09-28T09:00:00Z",
    createdById: 1,
    assignedToId: 2,
    tags: ["events","cron"],
  },
  {
    id: 7,
    title: "Remove legacy A/B flags",
    description: "Remove experiment flags from codebase.",
    status: "CANCELLED",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-07-01T09:00:00Z",
    createdById: 3,
    assignedToId: null,
    tags: ["techdebt"],
  },
  {
    id: 8,
    title: "Improve search fuzziness",
    description: "Make global ticket search tolerant to typos.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.MEDIUM,
    type: "FEATURE_REQUEST",
    createdAt: "2025-09-18T09:00:00Z",
    updatedAt: "2025-10-05T12:30:00Z",
    createdById: 2,
    assignedToId: 1,
    tags: ["search","ux"],
  },
  {
    id: 9,
    title: "Billing address validation",
    description: "Add server-side validation for billing addresses.",
    status: "OPEN",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.BUG,
    createdAt: "2025-10-05T14:00:00Z",
    updatedAt: "2025-10-05T14:00:00Z",
    createdById: 5,
    assignedToId: null,
    tags: ["billing"],
  },
  {
    id: 10,
    title: "Refactor ticket history model",
    description: "Split history by event types for easier querying.",
    status: "RESOLVED",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-25T08:00:00Z",
    updatedAt: "2025-09-10T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["backend","refactor"],
  },
  {
    id: 11,
    title: "TicTask Dashboard",
    description: "Start building out TicTask Dashboard with user view.",
    status: "CLOSED",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-25T08:00:00Z",
    updatedAt: "2025-09-10T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["frontend","design"],
  },
];