'use client';

import React from 'react';
import { Container, Typography, Divider, Box, Stack } from '@mui/material';

const DATA_COMPANY = 'TicTask';
const DATA_EFFECTIVE = 'December 31, 2026';

export default function DataPolicyPage() {
  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      <Stack spacing={3}>
        <Typography variant="h4" fontWeight={600}>{DATA_COMPANY} — Data Policy</Typography>
        <Typography variant="body2">Effective date: {DATA_EFFECTIVE}</Typography>

        <Divider />

        <Box>
          <Typography variant="h6" fontWeight={600} gutterBottom>1. Purpose and scope</Typography>
          <Typography paragraph>
            This Data Policy explains how {DATA_COMPANY} handles data generated by the Service, including technical, application, and user-provided data. It complements our Privacy Policy and describes operational practices.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>2. Types of data processed</Typography>
          <Typography paragraph>
            We process account data, project/task metadata, attachments you upload, logs and telemetry, and aggregated usage metrics. Sensitive personal data should not be uploaded unless explicitly requested.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>3. Purposes of processing</Typography>
          <Typography paragraph>
            Data is processed to operate the Service, provide features (search, notifications, collaboration), improve reliability/performance, and for security and fraud prevention.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>4. Data minimization & retention</Typography>
          <Typography paragraph>
            We aim to collect only data necessary for the stated purposes. Retention periods vary by data type; inactive accounts and associated data may be deleted after a reasonable retention period or upon user request, subject to backups and legal obligations.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>5. Backups and disaster recovery</Typography>
          <Typography paragraph>
            We keep encrypted backups and take standard disaster-recovery measures. Backups may contain personal data and will be retained according to our backup lifecycle; deletion from backups may take longer.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>6. Access control and security</Typography>
          <Typography paragraph>
            Access to production data is limited to authorized personnel on a least-privilege basis and logged. We use industry-standard encryption at rest and in transit and perform regular security assessments.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>7. Subprocessors and vendors</Typography>
          <Typography paragraph>
            We use subprocessors (e.g., cloud hosting, analytics, payment processors). A current list of subprocessors is available on request; subprocessors are contractually bound to protect data.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>8. Data subject requests & portability</Typography>
          <Typography paragraph>
            Users can request access, correction, deletion, or export of their data. Exported data is provided in common machine-readable formats (CSV, JSON) where technically feasible.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>9. Law enforcement and legal requests</Typography>
          <Typography paragraph>
            We may disclose data in response to lawful requests by public authorities. We evaluate requests carefully and will notify users where permitted by law.
          </Typography>

          <Typography variant="h6" fontWeight={600} gutterBottom>10. Contact</Typography>
          <Typography paragraph>
            For data-related inquiries or to request exports/removals, contact our support or legal team through the in-app support flow or by email.
          </Typography>
        </Box>
      </Stack>
    </Container>
  );
}
